# 21BCT0116

# SHRAVANI ARUN PATIL
# **ASSIGNMENT 1**

# TASK 1
-Create a pandas dataframe (Dataframe name as 'df') with numpy random values(4 features and 4 observation)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame(np.random.randint(50,size=(4,4)))
df

    0   1   2   3
0  22   4  23   4
1  46  46  44  41
2   9  39  20  39
3  22  27  35  33

# TASK 2
-Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'

In [ ]:
df.columns = ['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4']
df

   Random value 1  Random value 2  Random value 3  Random value 4
0              22               4              23               4
1              46              46              44              41
2               9              39              20              39
3              22              27              35              33

# TASK 3
-Find the descriptive statistics of the 'df' dataframe.

In [ ]:
df.describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean        24.750000       29.000000       30.500000       29.250000
std         15.435349       18.421003       11.090537       17.173138
min          9.000000        4.000000       20.000000        4.000000
25%         18.750000       21.250000       22.250000       25.750000
50%         22.000000       33.000000       29.000000       36.000000
75%         28.000000       40.750000       37.250000       39.500000
max         46.000000       46.000000       44.000000       41.000000

# TASK 4
-Check for the null values in 'df' and find the data type of the columns.

In [ ]:
df.isnull().any()

Random value 1    False
Random value 2    False
Random value 3    False
Random value 4    False
dtype: bool

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random value 1  4 non-null      int64
 1   Random value 2  4 non-null      int64
 2   Random value 3  4 non-null      int64
 3   Random value 4  4 non-null      int64
dtypes: int64(4)
memory usage: 256.0 bytes

# TASK 5
Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.

In [ ]:
df.loc[:,'Random value 2':'Random value 3']

   Random value 2  Random value 3
0               4              23
1              46              44
2              39              20
3              27              35

In [ ]:
df.iloc[:,1:3]

   Random value 2  Random value 3
0               4              23
1              46              44
2              39              20
3              27              35